name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Get latest tag for qBittorrent-Enhanced
        uses: oprypin/find-latest-tag@v1
        with:
          repository: c0re100/qBittorrent-Enhanced-Edition
        id: qbt-enhanced
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qbittorrent-enhanced-nox:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/qbittorrent-enhanced-nox:${{ steps.qbt-enhanced.outputs.tag }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/qbittorrent-enhanced-nox:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/qbittorrent-enhanced-nox:buildcache,mode=max
